baseURL = 'http://159.69.113.183:1313/'
languageCode = 'en-us'
title = 'Fairlinked'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 10

[params]
  user = "fairlinked"
  hostname = "fairlinked.eu"
  sitedescription = "The trade association and advocacy group for commercial Linkedin users"
  footerHtml = 'Copyright 2025-2026 by Fairlinked - Alliance for digital fairness e.V.'
  showMetadata = true

  [params.author]
    name = "Fairlinked"

  [params.styles]
    color = "orange"

  [[params.social]]
    key = 0
    name = "email"
    url = "mailto:hello@fairlinked.eu"

[menu]
  [[menu.header]]
    name = "About"
    weight = 0
    url = "/about"

[module]
  [[module.imports]]
    path = 'github.com/lordmathis/hugo-theme-nightfall'
